### PR TITLE
add code to convert stringtodecimal.change comment logic

### PR DESCRIPTION
**Pull request by hvysakhan**
ok ?

### CODE REVIEW

**Comment by ghost** [comment]
Commit message should be in present tense
e.g. Add code to convert string to decimal. Change comment logic

**Comment by ghost** [comment]
Anyways accepting :+1:

**Comment by hvysakhan** [comment]
ok

**Comment by hvysakhan** [comment]
done

**Comment by ghost** [comment]
You changed title here? I meant commit message :tongue:

**Comment by hvysakhan** [comment]
hohoho this will do for now

**Comment by ghost** [comment]
Okay Wait ...

**Comment by ghost** [comment]
Merged like a pro :+1: 

#no_merge_commit :laughing:

**Pull request merged**
